#************************************************加密规则配置***********************************************************#
#一、yml语法：以缩进表示层级。-表示数组。具体参考yml语法文档
#   注意 0开头的字符串需要加单引号 '0001'
#
#二、现支持的name：内部加密规则、授权服务器加密规则、通用加密规则、nb服务器加密规则、自定义加密规则
#   若name不是以上几种，则匹配为自定义加密规则
#
#三、通过 sid和name作为密码规则的唯一标识，若存在多个sid和name相同的密码规则，则会读取写在前面的那一个
#

secrets:
- sid: 140000000000000001
  app_secret_aes: ykt_2017_@%020_WZQITSTYUIJhd0802
  app_secret_md5: ykt*%_cO
  sm_secret_md5: applets_test_001
  name: "通用加密规则"

- sid: 140000000000000001
  app_secret_aes: ykt_2017_@%020_WZQITSTYUIJhd0802
  app_secret_md5: ykt*%_cO
  sm_secret_md5: applets_test_001
  name: "内部加密规则"

- sid: 6108168566885
  app_secret_aes: ykt_2017_@%020_WZQITSTYUIJhd5566
  app_secret_md5: test_001
  name: "授权服务器加密规则"

- sid: '00000001'
  app_secret_aes: ykt_2017_@%020_WZQITSTYUIJhd0802
  app_secret_md5: ykt*%_cO
  name: "nb服务器加密规则"
